version: '2'
services:
  dockerized:
    build:
      context: .
      dockerfile: Dockerfile.dockerized
    entrypoint:
      - sh
      - '-c'
    environment: []
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - go-cache:/go
    network_mode: host
volumes:
  go-cache: {}
